### ISSUE TITLE
T4 in VS2015 class library packages

### ISSUE THREAD

**Issue by brightertools** [tibitoth/TextTemplating#1]
Just a comment on using T4's in VS2015, although they have been added back in to asp.net 5 related project types, I can't get T4 to work with the FileManager to create multiple files in the new class library package projects... after trying a few examples, VS seems to hang without recovery after generating files... not sure if this is an issue across the board, or just my VS installation, but cant seem to get it to work..

Any comments appreciated.

**Comment by tibitoth** [comment]
I think it's a Visual Studio 2015 issue, but I haven't tried multiple files output in dnx projects with VS2015 yet.

**Comment by brightertools** [comment]
Thanks, it will be great if we can verify this as a one off or across the board, I am trying a new install to a VM, windows 10, VS2015 and will try again and see.

**Comment by tibitoth** [comment]
Can we close this?

**Comment by brightertools** [comment]
I reverted to using a standard class library and referencing that from an asp.net 5 project to get around the issue. I will need to look into this later... but creating multiple files from a class library package or creating multiple files from a normal class library project into a class library package project also crached Visual studio.
