### ISSUE TITLE
Error when trying to add dependency

### ISSUE THREAD

**Issue by akshayKhot** [tibitoth/TextTemplating#2]
When I add `"TextTemplating": "1.0.0-rc1-final"` dependency in my project.json file, I get following error: `Unable to locate Dependency TextTemplating >= 1.0.0-rc1-final`. 
I am using VS2015(update 2) and ASP.NET core.

**Comment by tibitoth** [comment]
I just published a nuget package for RC1. Now you have to able to restore this package in the project.json.
