### ISSUE TITLE
Cannot find on NPM

### ISSUE THREAD

**Issue by wjonesy** [tibitoth/TextTemplating#4]
Hello,

I can not find the package on npm.
https://www.npmjs.com/search?q=TextTemplating&page=1&ranking=optimal

Has it been removed?

**Comment by tibitoth** [comment]
Hi,

It's not an npm package, you can download it from NuGet https://www.nuget.org/packages/TextTemplating/ but unfortunately it uses a really old version of .NET Core. :(

**Comment by wjonesy** [comment]
Apologies.

I am getting confused between project.json and package.json.

Thanks for the reply.
